### ISSUE TITLE
Cheating on Fg image?

### ISSUE THREAD

**Issue by Lewislou** [qic999/PCTrans#2]
Why would Fg images be used in the testing stage in test_cvppp and eval_cvppp functions in trainer.py?
![image](https://github.com/qic999/PCTrans/assets/23080469/3d381604-b7f9-4b9f-a36b-cd26de0161f7)
Removing this Fg multiplication 'seg_outputs = seg_outputs * fg' would cause a large performance downgrade.

**Comment by qic999** [comment]
@Lewislou Thanks for your interest in our work. CVPPP Challenge provides FG masks in the test stage, and it is allowed to use FG masks to filter out prediction. Besides, the results of all baselines also use the FG masks in the test stage, which can be seen in their codes.

**Comment by Lewislou** [comment]
I see, thanks for your quick response.
